# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myappresources.my.api.group
spec:
  scope: Namespaced
  group: my.api.group
  names:
    plural: myappresources
    singular: myappresource
    kind: MyAppResource
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources: { status: { } }  # comment/uncomment for experiments
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                replicaCount:
                  type: integer
                resources:
                  type: object
                  properties:
                    memoryLimit:
                      type: string
                    cpuRequest:
                      type: string
                image:
                  type: object
                  properties:
                    repository:
                      type: string
                    tag:
                      type: string
                ui:
                  type: object
                  properties:
                    color:
                      type: string
                    message:
                      type: string
                redis:
                  type: object
                  properties:
                    enabled:
                      type: boolean
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Children
          type: string
          priority: 0
          jsonPath: .status.create_fn.children
          description: The children pods created.
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.create_fn.message
          description: As returned from the handler (sometimes).