apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo-operator
  namespace: "default"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: podinfo-operator
  template:
    metadata:
      labels:
        application: podinfo-operator
    spec:
      serviceAccountName: podinfo-account
      containers:
      - name: podinfo-operator
        image: mohitsharma44/podinfo_operator
        resources:
          limits:
            cpu: "1"
            memory: "256Mi"
          requests:
            cpu: "0.5"
            memory: "128Mi"
